# Generated by Django 4.1 on 2022-09-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventory1',
            fields=[
                ('material_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=200)),
                ('remark', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
