# Generated by Django 4.1 on 2022-09-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_inventory1_id_alter_inventory1_material_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory1',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
