# Generated by Django 4.1 on 2022-09-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_inventory1_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory1',
            name='date_added',
        ),
        migrations.AddField(
            model_name='inventory1',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory1',
            name='unit',
            field=models.CharField(default='nos', max_length=20),
            preserve_default=False,
        ),
    ]
