# Generated by Django 4.1 on 2022-09-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_inventory1_date_added_inventory1_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory1',
            name='inv_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
