# Generated by Django 4.1 on 2022-09-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_inventory1_inv_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inv_id', models.CharField(max_length=20)),
                ('material_code', models.CharField(max_length=100)),
                ('material_name', models.CharField(max_length=200)),
                ('in_out', models.CharField(max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('issued_to', models.CharField(max_length=200)),
                ('remark', models.CharField(max_length=200)),
            ],
        ),
    ]
