# Generated by Django 4.1 on 2022-09-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='unit',
        ),
        migrations.AddField(
            model_name='transactions',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
